// Schwarze Karten (Fragen/Prompts) - 80+ Karten
const blackCards = [
  // KI & Prompts
  "Der neue ChatGPT-Prompt für die Geschäftsführung: _____",
  "Unser KI-Assistent hat gelernt: _____",
  "Was ChatGPT wirklich über deinen Code denkt: _____",
  "Der Prompt, der zu ehrlich war: _____",
  "Copilot hat vorgeschlagen: _____",
  "Die dümmste KI-Halluzination: _____",
  "Das Midjourney-Prompt für den neuen CEO: _____",
  "System Prompt der HR-Abteilung: _____",
  "Was passiert, wenn man Temperature auf 2.0 stellt: _____",
  "Der Grund, warum das LLM verrückt spielt: _____",
  "Fine-tuning am Freitagnachmittag führte zu: _____",
  "Das RAG-System hat gefunden: _____",
  "Embeddings für _____ machen keinen Sinn.",
  "GPT-4 weigert sich zu antworten auf: _____",
  "Der neue Use Case für unsere KI: _____",
  "Das Token-Limit wurde überschritten wegen: _____",
  "Prompt Injection Beispiel aus der Praxis: _____",
  "Was DALL-E wirklich generiert hat: _____",
  "Der Context Window ist voll mit: _____",
  "Vector Database-Chaos verursacht durch: _____",
  
  // Meetings & Kommunikation
  "Die beste Ausrede für ein verpasstes Meeting: _____",
  "Slack-Nachricht um 23:59 Uhr: _____",
  "Zoom-Meeting-Hintergrund, der zu weit ging: _____",
  "Stand-Up um 9 Uhr, aber eigentlich: _____",
  "Was wirklich in den Meeting-Notes steht: _____",
  "Daily um 7 Uhr morgens, alle denken: _____",
  "Retrospektive, die ehrliche Antwort wäre: _____",
  "Sprint Planning eskaliert wegen: _____",
  "Das All-Hands-Meeting enthüllte: _____",
  "Die wahre Bedeutung von 'Lass uns das offline besprechen': _____",
  "Kamera aus im Call, weil: _____",
  "Das Meeting hätte eine E-Mail sein können über: _____",
  "Passive-aggressive Slack-Reaktion für: _____",
  "Teams-Status 'Beschäftigt' bedeutet eigentlich: _____",
  "Die 3-Stunden-Konferenz war über: _____",
  
  // Büroalltag
  "Das neue Feature, das niemand wollte: _____",
  "Der wahre Grund für den Serverausfall: _____",
  "Das Geheimnis produktiver Homeoffice-Tage: _____",
  "Der Grund, warum die Demo fehlschlug: _____",
  "Was in der Firmenkantine wirklich passiert: _____",
  "Die ehrliche Antwort auf 'Wie geht's?': _____",
  "Freitagnachmittag um 16:55 Uhr: _____",
  "Der wahre Grund für Homeoffice: _____",
  "Was niemand in der Toilette erwartet: _____",
  "Die Kühlschrank-Notiz eskalierte zu: _____",
  "Return-to-Office scheitert an: _____",
  "Der Grund für die Verzögerung: _____",
  "Montagmorgen 8 Uhr: _____",
  "Das Büro-Geheimnis: _____",
  "Die wahre Produktivitätskiller: _____",
  
  // Agile & Prozesse
  "Das nächste agile Buzzword: _____",
  "Warum das Sprint-Ziel nicht erreicht wurde: _____",
  "SCRUM Master verkündet: _____",
  "Die neue Jira-Policy verbietet: _____",
  "Definition of Done umfasst jetzt: _____",
  "Das Blocker im Stand-Up: _____",
  "Velocity gesunken wegen: _____",
  "Refinement-Meeting Ergebnis: _____",
  "Burndown-Chart erklärt durch: _____",
  "Story Points vergeben für: _____",
  
  // Tech & Code
  "Legacy Code von 2003 enthält: _____",
  "Der Production-Deploy am Freitag: _____",
  "Stack Overflow ist down, also: _____",
  "Der Bug, der ein Feature wurde: _____",
  "Code Review Kommentar: _____",
  "Merge Conflict gelöst mit: _____",
  "Tech Debt verursacht durch: _____",
  "Das Testing-Framework hasst: _____",
  "Debugging um 3 Uhr nachts enthüllt: _____",
  "Git Commit Message: '_____'",
  "Hotfix für: _____",
  "Refactoring führte zu: _____",
  "Serverless bedeutet eigentlich: _____",
  "Microservices-Chaos wegen: _____",
  "Der Container crashed wegen: _____",
  
  // Management & HR
  "Stakeholder ohne Ahnung fordert: _____",
  "Der CTO beim Prompt Engineering: _____",
  "Plötzliche Pivot-Entscheidung: _____",
  "Die 47. Umstrukturierung bringt: _____",
  "OKRs dieses Quartal: _____",
  "Performance Review enthüllt: _____",
  "Unlimited PTO bedeutet: _____",
  "Das neue Benefit: _____",
  "Vision Board im Konferenzraum zeigt: _____",
  "Cringe LinkedIn-Post vom Chef über: _____",
  "HR-Policy-Änderung verbietet: _____",
  "Townhall-Ankündigung: _____",
  "Corporate Wellness-Programm umfasst: _____",
  "Team-Building-Event: _____",
  "Diversity-Training über: _____",
  
  // Absurd & Fun
  "Was wirklich im Serverraum passiert: _____",
  "Der Praktikant hat entdeckt: _____",
  "IT-Support-Ticket #4731: _____",
  "Das Geheimnis des 10x-Engineers: _____",
  "Wie man den Product Owner beruhigt: _____",
  "Die Wahrheit über Pair Programming: _____",
  "Blockchain-Lösung für: _____",
  "Der wahre Grund für NFTs: _____",
  "Web3 revolutioniert: _____",
  "Metaverse-Meeting über: _____"
];

// Weiße Karten (Antworten) - 200+ Karten
const whiteCards = [
  // KI & Tech
  "Halluzinierende LLMs",
  "Prompt Injection",
  "Token-Limit erreicht",
  "Temperature auf 2.0",
  "Infinite Context Windows",
  "Fine-tuning am Freitagnachmittag",
  "Embeddings ohne Sinn",
  "Vector Databases, die niemand versteht",
  "RAG ohne Retrieval",
  "System Prompts mit Persönlichkeit",
  "Overfitted Models",
  "Tokenizer-Chaos",
  "Latency-Probleme beim Demo",
  "ChatGPT als Praktikant",
  "KI-generierte Entschuldigungen",
  "Der Praktikant trainiert jetzt GPT-5",
  "Pair Programming mit ChatGPT",
  "Copilot schreibt besseren Code",
  "Anthropic Claude im Stealth Mode",
  "OpenAI Drama auf Twitter",
  "Stable Diffusion NSFW Filter",
  "LangChain-Spaghetti-Code",
  "Pinecone Vector Database Down",
  "Hugging Face Model Hub Chaos",
  "Reinforcement Learning from Human Feedback",
  "Zero-Shot Prompting",
  "Few-Shot Learning Gone Wrong",
  "Chain-of-Thought Reasoning",
  "Constitutional AI Principles",
  "Multimodal Models",
  "Open-Source LLMs",
  "Quantized Models",
  "LoRA Fine-Tuning",
  "Prompt Engineering als Karriere",
  "AI Safety Alignment",
  "Emergent Abilities",
  "Mechanistic Interpretability",
  "Red Teaming",
  "Jailbreaking ChatGPT",
  "Synthetic Data Generation",
  
  // Büro & Alltag
  "Der verfaulte Döner in der Büroküche",
  "Kaffee-Automaten-Philosophie",
  "Passive-aggressive E-Mails",
  "Die Cloud ist down",
  "Ungefragte Screenshares",
  "Micromanagement per Slack",
  "Zoom-Fatigue",
  "Bureaucratic Overhead",
  "Return-to-Office-Mandate",
  "Das Daily um 7 Uhr morgens",
  "Der kaputte Drucker im 3. Stock",
  "Kostenloses Obst (aber nur Montags)",
  "Unlimited PTO (die niemand nimmt)",
  "Pizza-Parties statt Gehaltserhöhung",
  "Mandatory Fun Activities",
  "Open-Plan-Office-Hölle",
  "Corporate Wellness Programme",
  "Büro-Pflanzen, die langsam sterben",
  "Der Kollege, der nie sein Mikro ausmacht",
  "Kalter Kaffee vom Morgen",
  "Die Klimaanlage auf Arktis",
  "Schlechtes WLAN",
  "Kaffeemaschine kaputt seit 3 Wochen",
  "Parkplatz-Krieg",
  "Shared Desks",
  "Die einsame Banane im Kühlschrank",
  "Mikrowellen-Fisch",
  "Temperatur-Thermostat-Kriege",
  "Standing Desks, die niemand nutzt",
  "Ergonomische Tastaturen",
  "Herman Miller Aeron Chairs",
  "Whiteboard Marker alle leer",
  "Post-Its überall",
  "Kabelsalat",
  "Der stinkende Schuh unterm Tisch",
  
  // Meetings & Kommunikation
  "Endlose Refinement-Meetings",
  "Ungefragte Code Reviews",
  "Synergien synergisieren",
  "Asynchrone Kommunikation im Synchron-Call",
  "Die wahre Bedeutung von 'Done'",
  "Das Imposter-Syndrom",
  "Cringe LinkedIn-Posts vom Chef",
  "Sinnlose KPIs",
  "Die 47. Umstrukturierung",
  "Spontanes All-Hands um 16:55 Uhr",
  "Meetings, die E-Mails hätten sein können",
  "Stakeholder ohne Ahnung",
  "SCRUM Master auf Machttrip",
  "Retrospektiven, die nichts ändern",
  "Plötzliche Pivot-Entscheidungen",
  "Die neue Jira-Policy",
  "Hallway-Gespräche über Kubernetes",
  "Unironische Verwendung von 'Synergy'",
  "Circle Back",
  "Let's take this offline",
  "Parking Lot",
  "Low-hanging Fruit",
  "Think outside the box",
  "Leverage our resources",
  "Move the needle",
  "Drill down",
  "Boil the ocean",
  "Drink the Kool-Aid",
  "Ideate",
  "Deliverables",
  "Bandwidth",
  "Visibility",
  "Deep dive",
  "Quick win",
  "Game changer",
  "Best practices",
  "Core competency",
  
  // Agile & Prozesse
  "Sprint Planning Chaos",
  "Velocity Tracking",
  "Definition of Done Diskussionen",
  "Story Point Poker",
  "Burndown Charts",
  "Kanban Board Chaos",
  "WIP Limits ignoriert",
  "Blocker seit 3 Sprints",
  "Tech Debt Mountain",
  "Code Freeze",
  "Feature Flags überall",
  "Trunk-Based Development",
  "GitFlow Branching Strategy",
  "Semantic Versioning",
  "Breaking Changes",
  "Backwards Compatibility",
  "Deprecation Warnings",
  
  // Tech & Code
  "Legacy Code von 2003",
  "Der Production-Deploy am Freitag",
  "Stack Overflow ist down",
  "Der Bug, der ein Feature wurde",
  "Serverless, aber Server crasht trotzdem",
  "Regex, die niemand lesen kann",
  "Der neueste Hype-Cycle",
  "Blockchain für die Kaffeemaschine",
  "Deadline am Freitag, 17 Uhr",
  "Merge Conflicts",
  "Circular Dependencies",
  "Memory Leaks",
  "Race Conditions",
  "Null Pointer Exceptions",
  "Buffer Overflows",
  "SQL Injection",
  "XSS Vulnerabilities",
  "CORS Errors",
  "404 Not Found",
  "500 Internal Server Error",
  "DNS Issues",
  "SSL Certificate expired",
  "Load Balancer fail",
  "Database Migration gone wrong",
  "Cache Invalidation",
  "Distributed System Chaos",
  "CAP Theorem",
  "Eventually Consistent",
  "Sharding Nightmares",
  "N+1 Query Problem",
  "MongoDB ist web scale",
  "PostgreSQL vs MySQL Kriege",
  "NoSQL für alles",
  "Graph Databases",
  "Time Series Data",
  "ACID Transactions",
  "Two-Phase Commit",
  
  // DevOps & Infrastructure
  "Docker Container crashed",
  "Kubernetes Pods failing",
  "Terraform State locked",
  "AWS Outage",
  "Azure ist down",
  "GCP Billing Shock",
  "CI/CD Pipeline broken",
  "Jenkins Job failed",
  "GitHub Actions timeout",
  "Secrets committed to Git",
  "Production Database DROP",
  "Backup restore failed",
  "DDoS Attack",
  "Zero-Day Exploit",
  "Log4j Vulnerability",
  "Supply Chain Attack",
  "Compromised API Keys",
  
  // Management & Corporate
  "Quantified Self am Arbeitsplatz",
  "Corporate Jargon Bingo",
  "Die HR-Policy-Änderung",
  "Die Wahrheit über Tech-Bros",
  "Vision Board im Konferenzraum",
  "Open-Source-Drama auf Twitter",
  "OKRs die niemand versteht",
  "Quarterly Business Reviews",
  "Annual Performance Review",
  "360-Degree Feedback",
  "Peer Reviews",
  "Skip-Level Meetings",
  "One-on-Ones",
  "PIP (Performance Improvement Plan)",
  "Layoffs",
  "Hiring Freeze",
  "Reorg",
  "Acquihire",
  "Golden Handcuffs",
  "Equity Vesting Cliff",
  "Stock Options unter Wasser",
  "IPO Verzögerung",
  "Series B Funding",
  "Burn Rate",
  "Runway",
  "Pivot or Die",
  "Fail Fast",
  "Move Fast and Break Things",
  "Fake it till you make it",
  
  // Trends & Hypes
  "Web3 Revolution",
  "NFT Avatars",
  "Metaverse Offices",
  "Crypto Winter",
  "DeFi Collapse",
  "DAO Governance",
  "Smart Contracts bugs",
  "Meme Stocks",
  "Dogecoin to the moon",
  "Bitcoin Pizza Day",
  "Blockchain for everything",
  "Disruption",
  "Innovation Theater",
  "Growth Hacking",
  "Viral Marketing",
  "Influencer Partnership",
  "Thought Leadership",
  "Personal Branding",
  
  // Remote Work
  "Pants optional",
  "Kids screaming im Background",
  "Katze über Tastatur",
  "Vergessen zu unmuten",
  "Screen Share Fail",
  "VPN Probleme",
  "Zeitzone Chaos",
  "Async Standups",
  "Slack Threads Chaos",
  "Email Overload",
  "Calendar Tetris",
  "Zoom Bombing",
  "Virtual Happy Hour",
  "Digital Nomad Life",
  "Coworking Space",
  
  // Sonstiges
  "Imposter Syndrom",
  "Burnout",
  "Work-Life-Balance (nonexistent)",
  "Sabbatical",
  "Quiet Quitting",
  "Rage Applying",
  "The Great Resignation",
  "Boomerang Employees",
  "Job Hopping",
  "Career Ladder",
  "Glass Ceiling",
  "Peter Principle",
  "Dunning-Kruger Effect",
  "Survivorship Bias",
  "Sunk Cost Fallacy",
  "Analysis Paralysis",
  "Bikeshedding",
  "Yak Shaving",
  "Scope Creep",
  "Feature Creep",
  "Gold Plating",
  "Technical Debt",
  "Conway's Law",
  "Brooks's Law",
  "Parkinson's Law"
];

module.exports = { blackCards, whiteCards };
