// Schwarze Karten (Fragen/Prompts) - 100+ Karten
const blackCards = [
  // KI im Büroalltag
  "ChatGPT hat meine E-Mail geschrieben, aber vergessen: _____",
  "Ich habe ChatGPT gefragt, wie ich _____",
  "Die KI hat vorgeschlagen, das Meeting zu ersetzen durch: _____",
  "Unser Chef denkt, KI kann _____",
  "Der Praktikant hat ChatGPT benutzt für: _____",
  "Die automatische E-Mail-Antwort klang verdächtig nach: _____",
  "KI-generierte Präsentation, aber es fehlt: _____",
  "ChatGPT wurde gebeten, den Firmennewsletter zu schreiben über: _____",
  "Die KI hat meinen Kalender organisiert und dabei _____",
  "Kollege nutzt KI, um zu vermeiden: _____",
  "Der KI-Chatbot auf unserer Website antwortet auf Beschwerden mit: _____",
  "Chef hat eine KI-App entdeckt für: _____",
  "Die Zoom-KI hat automatisch zusammengefasst: _____",
  "KI-Übersetzung hat 'Sehr geehrte Damen und Herren' übersetzt als: _____",
  "Das KI-Tool für Produktivität empfiehlt: _____",
  
  // Großraumbüro-Probleme  
  "Das Schlimmste am Großraumbüro ist: _____",
  "Der Kollege am Nachbartisch macht ständig: _____",
  "Die Klimaanlage im Büro ist _____",
  "Jemand hat wieder _____ in der Mikrowelle gemacht.",
  "Das Meeting im Glaskasten nebenan ist über: _____",
  "Der Praktikant hat aus Versehen _____ in die Team-WhatsApp gepostet.",
  "Im Großraumbüro kann man nicht arbeiten wegen: _____",
  "Die neue Sitzordnung ist _____",
  "Der Kollege telefoniert seit 2 Stunden über: _____",
  "Gemeinschaftsküche-Drama: Jemand hat _____ geklaut.",
  "Open Space bedeutet: _____",
  "Der Lärmpegel im Büro kommt von: _____",
  "Heimlich im Büro: _____",
  "Die Toilette im 3. Stock ist bekannt für: _____",
  "Büropflanzen sterben wegen: _____",
  
  // Typische Kollegen
  "Der Kollege, der immer zu spät kommt, hat heute als Ausrede: _____",
  "Die Kollegin aus dem Marketing schwärmt von: _____",
  "Der IT-Kollege murrt über: _____",
  "Die Kollegin, die immer alles besser weiß, erklärt gerade: _____",
  "Der Praktikant wurde erwischt beim: _____",
  "Die Buchhaltung beschwert sich über: _____",
  "Der Vertriebs-Typ prahlt mit: _____",
  "Die Kollegin im Homeoffice ist eigentlich: _____",
  "Der Chef glaubt wirklich an: _____",
  "HR hat eine neue Regel gegen: _____",
  "Der Kollege, der immer Kekse mitbringt, bringt heute: _____",
  "Die Kollegin mit den 47 Katzen redet über: _____",
  "Der neue Mitarbeiter fragt ständig nach: _____",
  "Der Senior-Kollege erzählt zum 100. Mal von: _____",
  "Die Werkstudentin ist genervt von: _____",
  
  // Meetings
  "Das Meeting hätte wirklich _____ sein können.",
  "Zoom-Call, aber alle reden über: _____",
  "Der Chef hat im Meeting verkündet: _____",
  "Teams-Meeting um 8 Uhr morgens über: _____",
  "Bildschirm teilen, aber alle sehen: _____",
  "Das wöchentliche Meeting ist sinnlos, weil: _____",
  "Kamera aus, weil: _____",
  "Die Meeting-Einladung verspricht _____, dauert aber 2 Stunden.",
  "Im Hintergrund des Video-Calls sieht man: _____",
  "Das Brainstorming-Meeting hat ergeben: _____",
  "PowerPoint-Präsentation, Folie 47: _____",
  "Der Kollege hat sein Mikro nicht ausgemacht und man hört: _____",
  "Alle nicken im Meeting, aber niemand versteht: _____",
  "Meeting-Bingo gewonnen bei: _____",
  "Retrospektive: Was lief diese Woche schief? _____",
  
  // E-Mails & Kommunikation
  "E-Mail um 23:47 Uhr: _____",
  "Antwort auf 'Wie läuft's?': _____",
  "Die Betreffzeile lautet: _____",
  "CC an die ganze Firma wegen: _____",
  "Rechtschreibfehler in wichtiger E-Mail: _____",
  "Auto-Korrektur hat 'Liebe Grüße' geändert in: _____",
  "Die passive-aggressive E-Mail endet mit: _____",
  "Slack-Nachricht, 5 Minuten vor Feierabend: _____",
  "Der Kollege reagiert auf jede Nachricht mit: _____",
  "Out-of-Office-Nachricht: _____",
  "Die Antwort-Alle-Mail war über: _____",
  "Benachrichtigung: Du wurdest hinzugefügt zu: _____",
  "Der GIF in der Chat-Gruppe zeigt: _____",
  "Firmenchat um 6 Uhr morgens: _____",
  "Die wichtige Info ging unter, weil: _____",
  
  // Arbeitsalltag
  "Montagmorgen, 8 Uhr: _____",
  "Freitagnachmittag, 16:30 Uhr: _____",
  "Kaffeepause-Gespräch über: _____",
  "Die Mittagspause wird verbracht mit: _____",
  "Feierabend verzögert sich wegen: _____",
  "Produktivität gesteigert durch: _____",
  "Der Drucker funktioniert nicht wegen: _____",
  "WLAN ist langsam, weil: _____",
  "Passwort vergessen für: _____",
  "Die To-Do-Liste beginnt mit: _____",
  "Deadlines einhalten durch: _____",
  "Prokrastination mit: _____",
  "Bürostuhl kaputt wegen: _____",
  "Der Arbeitsplatz ist vollgestellt mit: _____",
  "Die beste Ausrede für einen freien Tag: _____",
  
  // Homeoffice vs. Büro
  "Homeoffice-Realität: _____",
  "Zurück ins Büro, aber: _____",
  "Homeoffice-Outfit: _____",
  "Im Büro vermisst man: _____",
  "Zu Hause abgelenkt durch: _____",
  "Der Postbote klingelt während: _____",
  "Katze/Hund im Video-Call: _____",
  "Homeoffice-Snacks: _____",
  "Der Paketbote denkt, ich bin: _____",
  "Arbeiten vom Bett aus führt zu: _____",
  
  // Sonstiges
  "Die Firmenfeier eskaliert bei: _____",
  "Team-Building-Event: _____",
  "Geschäftsreise-Highlight: _____",
  "Der Firmenparkplatz ist ein Kampf um: _____",
  "Büro-Wellness-Programm: _____",
  "Die neue App, die alle nutzen sollen: _____",
  "Gehaltsverhandlung, Argument: _____",
  "Fortbildung zum Thema: _____",
  "Die Kaffeemaschine ist kaputt, alle: _____",
  "Neuer Kollege, erster Eindruck: _____"
];

// Weiße Karten (Antworten) - 250+ Karten
const whiteCards = [
  // KI & Technologie
  "ChatGPT halluziniert",
  "KI schreibt bessere E-Mails als ich",
  "Vom Praktikanten mit ChatGPT erstellt",
  "Google-Suche war gestern",
  "KI-generierte Ausreden",
  "Alexa hört mit",
  "Siri versteht nur Bahnhof",
  "Automatische Übersetzung total falsch",
  "Rechtschreibkorrektur versagt",
  "Excel-Formeln kopiert ohne zu verstehen",
  "Tutorial von YouTube",
  "IT sagt 'Neustart'",
  "Passwort: Passwort123",
  "Browser-Tabs nie schließen",
  "WLAN-Probleme",
  "Akku leer",
  "Bildschirm eingefroren",
  "Kaffee über Tastatur",
  "Versehentlich 'Allen antworten'",
  "Screenshot statt scannen",
  
  // Großraumbüro
  "Lautes Telefonieren",
  "Schmatzen beim Essen",
  "Parfümwolke",
  "Schweißfüße",
  "Der stinkende Döner von gestern",
  "Kalter Kaffee vom Morgen",
  "Chips-Knistern",
  "Dauerhaftes Räuspern",
  "Tippgeräusche wie ein Maschinengewehr",
  "Private Gespräche überhören",
  "Klimaanlage auf Arktis",
  "Fenster-Kriegsführung",
  "Gemeinschaftskühlschrank-Chaos",
  "Ungespültes Geschirr",
  "Mikrowellen-Fisch",
  "Gestohlener Joghurt",
  "Schimmel im Kühlschrank",
  "Die einsame Banane",
  "Kaffeeflecken überall",
  "Müll neben dem Mülleimer",
  "Toilettenpapier alle",
  "Verstopfte Toilette",
  "Drucker-Stau",
  "Leerer Kopierer",
  "Kein Papier mehr",
  "Büropflanzen verdurstet",
  "Schreibtisch-Chaos",
  "Kabelgewirr",
  "Ergonomischer Albtraum",
  
  // Typische Kollegen & Verhalten
  "Der ewige Besserwisser",
  "Mikromanagement-Opfer",
  "Kaffeedieb",
  "Dauerredner",
  "Meeting-Marathon-Veranstalter",
  "Der Lautsprecher-Telefonierer",
  "Snack-Hoarder",
  "Gerüchteküche-Queen",
  "Montags-Miesepeter",
  "Freitags-Übermotivierte",
  "Ewiger Praktikant",
  "Burnout-Kandidat",
  "Selbstdarsteller",
  "Duckmäuser",
  "Cholerischer Chef",
  "Unfähige Führungskraft",
  "Mobber",
  "Schleimer",
  "Faulenzer",
  "Streber",
  "Nörgler",
  "Ja-Sager",
  "Wichtigtuer",
  "Tratsch-Tante",
  "Besserwisser-Bob",
  "Meeting-Marathonläufer",
  "PowerPoint-Präsentations-Peter",
  "Excel-Tabellen-Enthusiast",
  "E-Mail-Flut-Verursacher",
  "Ständig krank",
  "Immer zu spät",
  "Nie erreichbar",
  "Dauerpausler",
  "Arbeitswütiger",
  
  // Ausreden & Lügen
  "Der Hund hat meine Hausaufgaben gefressen",
  "Stau auf der A3",
  "Bahn hatte Verspätung",
  "Wecker nicht geklingelt",
  "Magen-Darm",
  "Migräne",
  "Familiärer Notfall",
  "Arzttermin",
  "Wichtiger Anruf",
  "Internet war weg",
  "E-Mail ist im Spam gelandet",
  "Hab's nicht gesehen",
  "War nicht in CC",
  "Hab ich anders verstanden",
  "Das war nicht klar kommuniziert",
  "Technische Probleme",
  "System war down",
  "Falsches Meeting im Kalender",
  "Doppelbuchung",
  "Vergessen",
  
  // Meetings
  "Sinnlose Besprechung",
  "Folien ohne Inhalt",
  "Endlosvortrag",
  "Nur Zuhören",
  "Niemand hat vorbereitet",
  "Alle starren auf's Handy",
  "Sidebar-Gespräche",
  "Einer redet, alle leiden",
  "Buzzword-Bingo",
  "Synergien nutzen",
  "Think outside the box",
  "Low hanging fruits",
  "Quick win",
  "Das müssen wir nochmal besprechen",
  "Nehmen wir offline",
  "Parken wir das mal",
  "Da kommen wir drauf zurück",
  "Zeitfresser",
  "Hätte eine E-Mail sein können",
  "Protokoll schreibt niemand",
  
  // Kommunikation
  "Passive-aggressive E-Mails",
  "Wie besprochen...",
  "Zur Kenntnisnahme",
  "Liebe Grüße, Tanja Gotthelf",
  "Mit freundlichen Grüßen",
  "MfG (unhöflich)",
  "!!! Wichtig !!!",
  "Dringend!",
  "Prio 1",
  "ASAP",
  "Können wir kurz telefonieren?",
  "Haben Sie kurz Zeit?",
  "Nur eine kurze Frage...",
  "Störe ich?",
  "Emoji-Flut",
  "Daumen hoch",
  "GIF-Gewitter",
  "Meme als Antwort",
  "Sprachnachrichten",
  "Voice-Mails",
  
  // Arbeitsalltag
  "Montagsblues",
  "Mittwochs-Motivationstief",
  "Freitagnachmittags-Feierstimmung",
  "Zu viel Kaffee",
  "Zu wenig Kaffee",
  "Zuckerrausch vom Süßigkeitenautomat",
  "Kantinen-Fraß",
  "Pommes zum Mittagessen",
  "Döner in der Pause",
  "Fastfood-Koma",
  "Überflüssige Meetings",
  "Deadlines ignorieren",
  "Prokrastination-Pro",
  "Reddit durchscrollen",
  "YouTube-Marathon",
  "Online-Shopping",
  "Private WhatsApp",
  "Instagram checken",
  "TikTok-Sucht",
  "Newsfeed aktualisieren",
  
  // Homeoffice
  "Im Schlafanzug",
  "Ohne Hose",
  "Netflix nebenbei",
  "Kind schreit im Hintergrund",
  "Katze auf Tastatur",
  "Hund bellt",
  "Postbote klingelt",
  "Nachbarn renovieren",
  "Straßenlärm",
  "Kühlschrank-Raids",
  "Snacken ohne Ende",
  "Mittagsschlaf",
  "Heimlich einkaufen",
  "Haushalt nebenbei",
  "Wäsche aufhängen",
  "Staubsaugen",
  "Kochen während dem Call",
  "Lieferando-Bestellung",
  "Bett als Arbeitsplatz",
  "Couch-Office",
  
  // Tech-Probleme
  "Kamera versehentlich an",
  "Mikro nicht stumm",
  "Falsches Meeting betreten",
  "Bildschirm geteilt (falscher Tab)",
  "Browser-Verlauf gezeigt",
  "Peinliche Tabs offen",
  "Benachrichtigungen eingeblendet",
  "Private Nachrichten sichtbar",
  "Screenshot-Fail",
  "Zoom-Hintergrund versagt",
  "Filter versehentlich aktiviert",
  "Als Kartoffel im Call",
  "Verbindung abgebrochen",
  "Audio-Echo",
  "Video ruckelt",
  "Bildschirm schwarz",
  "Falscher Bildschirm",
  "PowerPoint stürzt ab",
  "Excel friert ein",
  "Word speichert nicht",
  
  // Büro-Equipment
  "Kaputte Kaffeemaschine",
  "Defekter Drucker",
  "Papierstau",
  "Toner leer",
  "Kopierer macht Faxen",
  "Telefon klingelt dauernd",
  "Tastatur klebt",
  "Maus funktioniert nicht",
  "Bildschirm zu dunkel",
  "Stuhl quietscht",
  "Tisch wackelt",
  "Keine Steckdosen",
  "Ladekabel vergessen",
  "USB-Stick verloren",
  "Kopfhörer kaputt",
  "Headset-Akku leer",
  "Monitor ausgefallen",
  "Docking-Station zickt",
  "Laptop überhitzt",
  "Lüfter laut wie Flugzeug",
  
  // Absurdes
  "Würstchen-Wasser in der Kaffeetasse",
  "Nackt-Yoga im Meeting-Raum",
  "Chef tanzt auf dem Schreibtisch",
  "Praktikant schläft unterm Tisch",
  "Kollege weint in der Toilette",
  "Betrunkener Kunde",
  "Nervenzusammenbruch",
  "Existenzielle Krise",
  "Scheidungspapiere",
  "Liebeskummer",
  "Midlife-Crisis",
  "Lottogewinn",
  "Spontane Kündigung",
  "Wutausbruch",
  "Lachanfall",
  
  // Chef & Management  
  "Unfähige Geschäftsführung",
  "Unrealistische Erwartungen",
  "Ständige Umstrukturierung",
  "Neue Strategie (schon wieder)",
  "Budgetkürzungen",
  "Keine Gehaltserhöhung",
  "Leere Versprechungen",
  "Toxische Führungskultur",
  "Favoritismus",
  "Willkürliche Entscheidungen",
  "Inkompetenz",
  "Micromanagement",
  "Vertrauensmangel",
  "Fehlende Wertschätzung",
  "Überstunden unbezahlt",
  
  // HR & Regeln
  "Neue Compliance-Richtlinie",
  "Datenschutz-Schulung",
  "Pflicht-Webinar",
  "Feedback-Gespräch",
  "Zielvereinbarung",
  "Leistungsbeurteilung",
  "Abmahnung",
  "Kündigung",
  "Probezeit verlängert",
  "Personalakte",
  "Arbeitszeugnis",
  "Betriebsrat eingeschaltet",
  "Krank ohne Attest",
  "Zu viele Fehltage",
  "Unpünktlichkeit",
  
  // Sonstiges
  "Büro-Olympiade",
  "Weihnachtsfeier-Exzesse",
  "Sommerfest-Peinlichkeiten",
  "Team-Building-Horror",
  "Vertrauensübungen",
  "Kennenlern-Spiele",
  "Eisbrecher-Aktivitäten",
  "Firmenlauf",
  "Gesundheitstag",
  "Yoga-Kurs",
  "Massage-Angebot",
  "Obstkorb (leer)",
  "Gratis-Kaffee (schlecht)",
  "Tischkicker",
  "Playstation",
  "Ruheraum (nie frei)",
  "Schlafkabine",
  "Dachterrasse (gesperrt)",
  "Firmenparkplatz (zu klein)",
  "Kantine (ungenießbar)"
];

module.exports = { blackCards, whiteCards };
